### ISSUE TITLE
PROBLEM running frequenst version of 3conv3fc

### ISSUE THREAD

**Issue by smilesun** [felix-laumann/Bayesian_CNN#10]
```
python main_Frequentist.py --net_type "3conv3fc"  # original
using cuda

[Phase 1] : Data Preparation
| Preparing CIFAR-100 dataset...
| Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to ./data/cifar-100-python.tar.gz
100.0%
[Phase 2] : Model setup
| Building net type [3conv3fc]...
/root/host/paper_2019_rfms_representation/refactor_Bayesian_CNN/utils/FrequentistModels/AlexNet.py:8: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight, gain=np.sqrt(2))
/root/host/paper_2019_rfms_representation/refactor_Bayesian_CNN/utils/FrequentistModels/AlexNet.py:9: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias, 0)
Traceback (most recent call last):
  File "main_Frequentist.py", line 151, in <module>
    net.apply(conv_init)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 243, in apply
    fn(self)
  File "/root/host/paper_2019_rfms_representation/refactor_Bayesian_CNN/utils/FrequentistModels/AlexNet.py", line 8, in conv_init
    nn.init.xavier_uniform(m.weight, gain=np.sqrt(2))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'F3Conv3FC' object has no attribute 'weight'

```

**Comment by kumar-shridhar** [comment]
Hi @smilesun, 
As used in AlexNet and LeNet, use the conv_init function before the class definition in 3Conv3FC file:
`def conv_init(m):
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        nn.init.xavier_uniform(m.weight, gain=np.sqrt(2))
        nn.init.constant(m.bias, 0)
`
This should fix it.
